### ISSUE TITLE
Facebook Platform OAuth Flow

### ISSUE THREAD

**Issue by RohanNagar** [SanctionCo/pilot-ios#14]
Blocking Tasks:
 - [x] #13 Settings Page

Requirements:
- [x] The Facebook available platform section in the settings page kicks off the OAuth flow
- [x] The SFAuthenticationSession view sends the user to the Facebook OAuth URL
- [x] The callback receives the Facebook OAuth token and updates Thunder with a new user
- [x] The Facebook platform row moves in the settings to the connected accounts section

Related Work:
- #28 OAuth

Estimated Work Time: **1 week**

**Comment by NickEckert** [comment]
Done in #28
