### ISSUE TITLE
Change user email and password

### ISSUE THREAD

**Issue by RohanNagar** [SanctionCo/pilot-ios#16]
Blocking Tasks:
- [x] #13 Settings Page

Requirements:
- [ ] Change Email option in account information settings is functional
- [x] Change Password option in account information settings is functional
- [ ] The user can type a new email
- [x] The user can type a new password (and confirm it)
- [x] The new user object is updated in Thunder

Estimated Work Time: **3 days**

**Comment by NickEckert** [comment]
Partially implemented in #43 
Change email will be addressed in a new issue
