### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by RohanNagar** [SanctionCo/pilot-ios#17]
Blocking Tasks:
- [x] #13 Settings Page

Requirements:
- [x] The `Delete Account` option in the account information settings page is functional
- [x] The user is given a warning that deleting their account is permanent
- [x] Upon confirming, the DELETE request is sent to Thunder
- [x] The user sees a final confirmation that their account has been deleted, and then is taken to the initial login screen

Estimated Work Time: **5 days**

**Comment by NickEckert** [comment]
Added in #39
