### ISSUE TITLE
Settings child views need to be a UITableViewController

### ISSUE THREAD

**Issue by NickEckert** [SanctionCo/pilot-ios#22]
Currently there is a mix of tableView and non tableView elements. This causes elements not in the tableView to cover scrollable content that is in the tableView.

<img width="377" alt="settingspagecutoff" src="https://user-images.githubusercontent.com/8596671/30897959-9b429b9a-a31e-11e7-839c-68aa00fe7618.png">

**Comment by RohanNagar** [comment]
Fixed in #26
